sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 8

env:
  global:
    - secure: "E4T71MIB4/fYPnA7Ugg8u2WzEMOPEyg7IHMlfDU03OfQA58ItgDM9AtMhMPGFLcV0OmZsqPPmcda9bajooFVi/YWNT2SP+lLaB36tSYEvG+ak9KsFYax297gkOG+KUh/H+qYTLXYNAAdmqoq8KA5nm9BMsKRjGoXueQ2WrtLhZVYq1vXxOkdhgFJDj1z6toAGgJhqWZWg9HUfX0NAiXMZBlCjFqZDzxx9rExsZ6ARsFxo7Pa8J8rp05aF2Ozz9XjvlhbcbRenthdCmLurleU+LtIDxlriMmfMi+Hvfu6Yy8UQaReDrFnuBV7Jln5OmboidMce+lzJI+ND9I7w9rst9r32S1EcizKkEp++0BzrJuXBcjK9mm7Yw2a8Uc2mYXf/ZM7wbfYGGXOgdDmYErXs8lqG7tuEfHsEGVP3wRtjQ7iW+ViVgr8IvASnV8il3YhIKC6pgmsa3HeFjbWJsnSUNmp8BySIX2EzagrssdA/uxuRe6T9neNdYyMrbw775HHGnfbKTvNBDu9lmSDH/av0zwP/UEN0Bsww+3TzSXTsFvJMvRQk7sVk06ahmK43zE6q8kw7fh9oHyM+MTasUVKp46RiFZPo5Q356TOExC1k28ZSc6NadIemxVFJGTbDJW+mCHCrG+2v6QnfvOwV3zXYUkBjLLtOC5c+oruTvDvR5k="

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - npm run test
  - npm run e2e
  - npm run build
  - npm run build-ghpages

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then angular-cli-ghpages --dir="dist-ghpages" --repo="https://${GH_TOKEN}@github.com/RaphaelYan/ngx-deck.git" --name="Sr. Travis" --email="hi@travis.org"; fi

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: raphael.yan89@gmail.com
  api_key:
    secure: "J381S9YVe7EvPkzP55zTJPExuGgXoPTfbtpH9rE4e1IBCSSViE9Lnq8KrzzoNXF+Tm9V+ofrCwecddhdsAI2+PSZEjqBbrL1p1YwbhkMMwwyVmkBs3PFuCbbtTVaeDXXU0h88Sc2Akpjkcot3zQq33mgOP6OrO2ahhkRkRxWdS2+/WIlv4DyyT/2jDgAnnnJwrWZX/0rNf/gQGio/k4xpZghXa1KX4ur5uvfDtxZ3nTbBWaLuDUxg/lbnudS/dqcXJxliHjUUDeaDyf1c0AOCRgqtIQB81rg+LCx8xAUvi2kr/oEE0aUz4xkBYMF3oKaQqns0q0kiL/hURtQ+ophgwOF4ernZ4Zg8Z5aSlN9estKz0l4ci/+OuwusdDdS5tkQaL1zcSdcyKMNX6s9dw3uKbftN2tK5Lq+ZqZVXRq41QEBxV11gzkPtOy+OdEqXUuHgXNMZxEztR4+WRoG6ys7tMXHPoBj1yPVbY2WMIBBTTyjqB4fSOhtzaF+3EWHiY+6kUo4pHuVSXBPspPuUolpKHMojg0vHyXahSQAgMyiOeN0G6WNHaAo8w9wFgSyoXXLcqJLdsOGcewVUEppRt+ke6JD7qNslRqk98iHHZPoeom1B0aN45L8QFe6+boa9V9aZ2v3cGoP7HfAyfDEKk123wjdPsczAYU6alHr9s2wXw="
  on:
    branch: master
  skip_cleanup: true
